update infisical wrapper to detect if logged in already

diff --git a/scripts/tinymotion-backend-infisical b/scripts/tinymotion-backend-infisical
--- a/scripts/tinymotion-backend-infisical
+++ b/scripts/tinymotion-backend-infisical
@@ -1,10 +1,17 @@
-#!/bin/bash -e
+#!/bin/bash
+
+set -e
 
 # in case it is set already, it interferes with infisical login
 unset INFISICAL_TOKEN
 
-# TODO: only if not already logged in? (is there are way to tell?)
-infisical login
+# login to infisical if needed
+# at time of writing "infisical token" will return nonzero exit status if the
+# user is not currently logged and zero if logged in
+if ! infisical token >& /dev/null; then
+    # user is not logged in already
+    infisical login
+fi
 
 # run tinymotion backend with secrets injected
 infisical run --path /tinymotion_backend/app -- tinymotion-backend "$@"
